import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { execSync } from "child_process";
import { existsSync, watch as fsWatch } from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const linkToTestVault = {
  name: "link-to-test-vault",
  setup(build) {
    build.onEnd(result => {
      if (result.errors.length) return;
      if (!existsSync("scripts/link-to-test-vault.mjs")) return;
      try {
        execSync("node scripts/link-to-test-vault.mjs", { stdio: "inherit" });
      } catch {
        // non-fatal in watch mode
      }
    });
  },
};

const ctx = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  minify: prod,
  outfile: "main.js",
  plugins: prod ? [] : [linkToTestVault],
});

if (prod) {
  await ctx.rebuild();
  process.exit(0);
} else {
  await ctx.watch();
  // Re-copy styles.css to the test vault whenever it changes — esbuild only
  // watches TS sources.
  if (existsSync("styles.css")) {
    let cssTimer;
    fsWatch("styles.css", () => {
      clearTimeout(cssTimer);
      cssTimer = setTimeout(() => {
        try {
          execSync("node scripts/link-to-test-vault.mjs", { stdio: "inherit" });
        } catch {
          // non-fatal
        }
      }, 50);
    });
  }
}
